version: '3'

services:
  resume_srv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - username=
        - passwd=
    image: resume_srv
    container_name: resume_srv
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - app-network
    ports:
      - "22:22"
    volumes:
      - web-root:/home/${username}/srv/static
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html/static
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
    depends_on:
      - resume_srv
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html/static
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html/static --email --agree-tos --no-eff-email --force-renewal -d sda.ddns.net

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: D:\DEV_WORKSPACE\jsonresume-portfolio\dhparam
  #     o: bind

networks:
  app-network:
    driver: bridge