version: '3'

services:
  resume_srv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - username=
        - passwd=
    image: resume_srv
    container_name: resume_srv
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - app-network
    expose:
      - 22
      - 3000
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
    depends_on:
      - resume_srv
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email --agree-tos --no-eff-email --force-renewal -d sda.ddns.net

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: D:\DEV_WORKSPACE\jsonresume-portfolio\build\web\static
      o: bind
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: D:\DEV_WORKSPACE\jsonresume-portfolio\dhparam
  #     o: bind

networks:
  app-network:
    driver: bridge