version: '3'

services:
  resume_srv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=docker
        - PWD=drm123456
    image: resume_srv
    container_name: resume_srv
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - app-network
    ports:
      - "22:22"
    volumes:
      - web-root:/home/docker/srv/static
      - ./build/ssh/id_rsa.pub:/home/docker/.ssh/authorized_keys
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/static
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./build/dhparam:/etc/ssl/certs
    depends_on:
      - resume_srv
    networks:
      - app-network
  certbot:
    image: gordonchan/auto-letsencrypt
    container_name: certbot
    depends_on:
      - webserver
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/static
    environment:
      - EMAIL=dennis.shablonov@gmail.com
      - SERVER_CONTAINER=webserver
      - WEBROOT_PATH=/var/www/static
      - DOMAINS=shablonov.ddns.net
      - CHECK_FREQ=7

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge