version: '3'

services:
  resume_srv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${USR:-docker}
        - PWD=${PWD:-resume}
    image: resume_srv
    container_name: resume_srv
    restart: unless-stopped
    environment:
      - JSONRESUME_URL=${JSONRESUME_URL:?No jsonresume URL specified}
    networks:
      - app-network
    ports:
      - "22:22"
    volumes:
      - web-root:/home/${USR:-docker}/srv/static
      - ${PUBKEY}:/home/${USR:-docker}/.ssh/authorized_keys
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WEBROOT=${WEBROOT}
      - DOMAIN=${DOMAIN}
    volumes:
      - web-root:${WEBROOT:?No webroot path specified}
      - ./nginx-conf/${CURRENT_CFG:?No configuation specified}:/etc/nginx/conf.d
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./build/dhparam:/etc/ssl/certs
      - ./nginx-conf/template-variables.conf:/etc/nginx/templates/10-variables.conf.template
    depends_on:
      - resume_srv
    networks:
      - app-network
  certbot:
    image: gordonchan/auto-letsencrypt
    container_name: certbot
    depends_on:
      - webserver
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:${WEBROOT:?No webroot path specified}
    environment:
      - EMAIL=${EMAIL:?No email specified}
      - SERVER_CONTAINER=webserver
      - WEBROOT_PATH=${WEBROOT:?No webroot path specified}
      - DOMAINS=${DOMAIN:?No domain specified}
      - CHECK_FREQ=7
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge